import { expect, fireEvent, userEvent, waitFor, within } from 'storybook/test';

/** Exercise real controls and placements, including recovery from invalid geometry. */
export async function checkPhysicalRoom({ canvasElement }: { canvasElement: HTMLElement }) {
  // Ordinary browsing must never rearrange the scene or leave stress-test settings behind.
  if (import.meta.env.MODE !== 'test') return;
  const canvas = within(canvasElement);
  const input = (label: string, value: string) => fireEvent.change(canvas.getByRole('spinbutton', { name: label }), { target: { value } });
  const room = () => canvasElement.querySelector<HTMLElement>('.room')!;
  const camera = () => canvasElement.querySelector<HTMLElement>('.perspective')!;
  const pool = () => canvasElement.querySelector<HTMLElement>('.lamp-light')!;
  await waitFor(() => expect(pool().style.width).not.toBe(''));
  expect(canvas.getByLabelText('Desk width (mm) inches')).toHaveTextContent('47.24 in');
  fireEvent.change(canvas.getByRole('slider', { name: 'Desk width (mm) slider' }), { target: { value: '1600' } });
  await waitFor(() => expect(canvas.getByRole('spinbutton', { name: 'Desk width (mm)' })).toHaveValue(1600));
  expect(canvas.getByLabelText('Desk width (mm) inches')).toHaveTextContent('62.99 in');
  await waitFor(() => expect(camera().style.getPropertyValue('--perspective-width')).toBe('1920'));
  input('Desk depth (mm)', '1000');
  await waitFor(() => expect(canvasElement.querySelector('.desk-study__shadow')).toHaveAttribute('viewBox', '0 0 1920 1200'));
  expect(canvasElement.querySelector('.desk-study__shadow')).toHaveAttribute('viewBox', '0 0 1920 1200');
  expect(canvasElement.querySelector('.lamp-cast-shadow')).toHaveAttribute('viewBox', '0 0 1920 1200');
  const mug = canvas.getByRole('group', { name: /^Mug$/ });
  const desk = canvasElement.querySelector<HTMLElement>('.desk')!;
  const physicalWidth = () => parseFloat(getComputedStyle(mug).width) / parseFloat(getComputedStyle(desk).width) * 1920;
  expect(physicalWidth()).toBeCloseTo(168, 0);
  const before = Number(mug.style.getPropertyValue('--movable-x'));
  mug.focus();
  await userEvent.keyboard('{ArrowRight}{ArrowRight}');
  expect(Number(mug.style.getPropertyValue('--movable-x'))).toBe(before + 20);
  const lamp = canvas.getByRole('group', { name: 'Desk lamp' });
  lamp.focus();
  await userEvent.keyboard('{ArrowRight}{ArrowRight}');
  const lampX = lamp.style.getPropertyValue('--movable-x');
  const head = canvas.getByRole('button', { name: 'Turn the lamp off' });
  const shade = canvasElement.querySelector('.desk-lamp__shade')!;
  const originalPose = shade.innerHTML;
  const headBox = head.getBoundingClientRect();
  const aim = { pointerId: 1, button: 0, buttons: 1, clientX: headBox.left + headBox.width / 2, clientY: headBox.top + headBox.height / 2 };
  fireEvent.pointerDown(head, aim);
  fireEvent.pointerMove(head, { ...aim, clientX: aim.clientX + 30, clientY: aim.clientY + 20 });
  fireEvent.pointerUp(head, { ...aim, buttons: 0, clientX: aim.clientX + 30, clientY: aim.clientY + 20 });
  await waitFor(() => expect(shade.innerHTML).not.toBe(originalPose));
  // A dragged shade suppresses its trailing click; a new pointer-down starts a click.
  fireEvent.pointerDown(head, aim); fireEvent.pointerUp(head, { ...aim, buttons: 0 });
  fireEvent.click(head);
  await waitFor(() => expect(canvas.getByRole('button', { name: 'Turn the lamp on' })).toBeInTheDocument());
  const aimed = shade.innerHTML;
  input('Desk width (mm)', '3400');
  await waitFor(() => expect(camera().style.getPropertyValue('--perspective-width')).toBe('4080'));
  expect(canvas.getByRole('spinbutton', { name: 'Desk width (mm)' })).toHaveValue(3400);
  expect(canvas.getByRole('slider', { name: 'Desk width (mm) slider' })).toHaveValue('3000');
  fireEvent.change(canvas.getByRole('slider', { name: 'Desk width (mm) slider' }), { target: { value: '1600' } });
  await waitFor(() => expect(camera().style.getPropertyValue('--perspective-width')).toBe('1920'));
  input('Eye height (mm)', '');
  await expect(canvas.getByRole('alert')).toHaveTextContent('last valid scene');
  expect(lamp.style.getPropertyValue('--movable-x')).toBe(lampX);
  input('Eye height (mm)', '1650');
  await waitFor(() => expect(canvas.queryByRole('alert')).toBeNull());
  expect(lamp.style.getPropertyValue('--movable-x')).toBe(lampX);
  expect(shade.innerHTML).toBe(aimed);
  await userEvent.click(canvas.getByRole('button', { name: 'Turn the lamp on' }));
  input('Setback (mm)', '0');
  await waitFor(() => expect(Number(camera().style.getPropertyValue('--perspective-angle'))).toBe(90));
  const position = Number(mug.style.getPropertyValue('--movable-x'));
  const box = mug.getBoundingClientRect();
  const pointer = { pointerId: 1, button: 0, buttons: 1, clientX: box.left + box.width / 2, clientY: box.top + box.height / 2 };
  fireEvent.pointerDown(mug, pointer);
  fireEvent.pointerMove(mug, { ...pointer, clientX: pointer.clientX + 40 });
  fireEvent.pointerUp(mug, { ...pointer, buttons: 0, clientX: pointer.clientX + 40 });
  await waitFor(() => expect(Number(mug.style.getPropertyValue('--movable-x'))).toBeGreaterThan(position));
  input('Eye height (mm)', '850');
  await waitFor(() => expect(canvasElement.querySelector('.room__diagnostic')).toHaveTextContent('100.0 mm'));
  for (const node of canvasElement.querySelectorAll('[style], [transform]'))
    expect(`${node.getAttribute('style')} ${node.getAttribute('transform')}`).not.toMatch(/NaN|Infinity/);
  input('Eye height (mm)', '700');
  await expect(canvas.getByRole('alert')).toHaveTextContent('eye height above tabletop');
  input('Eye height (mm)', '1650');
  await waitFor(() => expect(room()).not.toBeNull());
  input('Light intensity', '0');
  await waitFor(() => expect(pool().style.visibility).toBe('hidden'));
  expect(canvasElement.querySelector<SVGCircleElement>('.desk-room__pool')!.style.visibility).toBe('hidden');
  input('Light intensity', '3');
  await waitFor(() => expect(pool().style.filter).toBe('brightness(3)'));
  const size = parseFloat(pool().style.width);
  input('Pool spread', '2.8');
  await waitFor(() => expect(parseFloat(pool().style.width)).toBeCloseTo(size * 2, 5));
  input('Setback (mm)', '650');
  await waitFor(() => expect(Number(camera().style.getPropertyValue('--perspective-angle'))).toBeCloseTo(54.1623, 3));
}
